Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Admin.Models;
using System.Data.SqlClient;

namespace Admin.Controllers
{
    public class SliderController : Controller
    {
        private Modelo db = new Modelo();
        // GET: Slider
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FonixEresTu()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "FONIX_ERES_TU").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }


        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(ImagenesView ImagenesView)
        {
            if (ModelState.IsValid)
            {
                var url = "";
                var pic = string.Empty;
                var folder = "";
                if (ImagenesView.APARTADO == "FONIX_ERES_TU")
                {
                    folder = "/imagenes/eres_tu";
                    url = "FonixEresTu";
                }
                else if (ImagenesView.APARTADO == "EVENTOS")
                {
                    folder = "/imagenes/eventos";
                    url = "Eventos";
                }
                else if (ImagenesView.APARTADO == "BIENVENIDO")
                {
                    folder = "/imagenes/bienvenido";
                    url = "Bienvenidos";
                }
                else { folder = "/imagenes/clasificados"; url = "Clasificados"; }
                using (var transaccion = db.Database.BeginTransaction())
                {
                    try
                    {
                        if (ImagenesView.ImagenFile != null)
                        {
                            pic = FilesHelper.UploadPhoto(ImagenesView.ImagenFile, folder);
                            pic = string.Format("{0}/{1}", folder, pic);
                        }

                        var imagen = ToImagenes(ImagenesView);
                        imagen.IMAGEN = pic;
                        db.IMAGENES.Add(imagen);
                        transaccion.Commit();
                        db.SaveChanges();


                        return RedirectToAction(url);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = "Error: " + ex.Message + "//" + ex.InnerException;
                        return View(ImagenesView);

                    }

                }


            }

            return View(ImagenesView);

        }

        public ActionResult Comunicados()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "COMUNICADOS").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }

        public ActionResult Clasificados()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "CLASIFICADOS").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }

        public ActionResult Eventos()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "EVENTOS").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }


        public ActionResult Bienvenidos()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "BIENVENIDO").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }


        private IMAGENES ToImagenes(ImagenesView view)
        {
            return new IMAGENES
            {
                ID = view.ID,
                APARTADO = view.APARTADO,
                IMAGEN = view.IMAGEN,
                ORDEN = view.ORDEN,
                DESCRIPCION = view.DESCRIPCION
            };
        }



        public ActionResult EliminarImagen(int? id)
        {
            var imagen = db.IMAGENES.Find(id);
            return View(imagen);
        }


        public ActionResult ColoresCumple()
        {
            var imagenes = db.IMAGENES.Where(x => x.APARTADO == "CUMPLEANIOS").OrderBy(x => x.ORDEN);
            return View(imagenes.ToList());
        }


        public void ActualizarColores(string colorf,string colorn, string colord)
        {

            var query = db.Database.ExecuteSqlCommand("UPDATE PORTAL.IMAGENES set DESCRIPCION=@color1 WHERE ID=124", new SqlParameter("@color1", colorf));
            var query2 = db.Database.ExecuteSqlCommand("UPDATE PORTAL.IMAGENES set DESCRIPCION=@color2 WHERE ID=125", new SqlParameter("@color2", colorn));
            var query3 = db.Database.ExecuteSqlCommand("UPDATE PORTAL.IMAGENES set DESCRIPCION=@color3 WHERE ID=126", new SqlParameter("@color3", colord));

            //return OK;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarImagen(IMAGENES imagen)
        {
            var query = db.IMAGENES.Find(imagen.ID);

            db.IMAGENES.Remove(query);
            db.SaveChanges();

            if (query.APARTADO == "FONIX_ERES_TU")
            {
                return RedirectToAction("FonixEresTu");
            }
            else if (query.APARTADO == "EVENTOS")
            {
                return RedirectToAction("Eventos");
            }
            else if (query.APARTADO == "BIENVENIDO")
            {
                return RedirectToAction("Bienvenidos");
            }
            else { return RedirectToAction("Clasificados"); }

        }
    }
}

Admin/Views/Slider/Agregar.cshtml
@model Admin.Models.ImagenesView

@{
    ViewBag.Title = "Agregar";
}


@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <h3>@ViewBag.Error</h3>
}
<h2>Agregar</h2>


@using (Html.BeginForm("Agregar", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IMAGENES</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.APARTADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Request.QueryString["tipo"] == "fet")
                {
                    <input type="text" name="APARTADO" id="APARTADO" value="FONIX_ERES_TU">
                }
                else if (Request.QueryString["tipo"] == "ev")
                {
                    <input type="text" name="APARTADO" id="APARTADO" value="EVENTOS">
                }
                else if (Request.QueryString["tipo"] == "bv")
                {
                    <input type="text" name="APARTADO" id="APARTADO" value="BIENVENIDO">
                }
                else
                {
                    <input type="text" name="APARTADO" id="APARTADO" value="CLASIFICADOS">
                }

                @Html.ValidationMessageFor(model => model.APARTADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMAGEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.IMAGEN, new { htmlAttributes = new { @class = "form-control" } })*@
                @*<input type="file" name="file" id="file" />*@
                @Html.TextBoxFor(modelo => modelo.ImagenFile, new { type = "file" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.FECHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ORDEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ORDEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ORDEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Admin/Views/Slider/Bienvenidos.cshtml
@model IEnumerable<Admin.Models.IMAGENES>

@{
    ViewBag.Title = "Bienvenidos";
}

<h2>Clasificados</h2>

<p>
    @*@Html.ActionLink("Agregar", "Agregar")*@
    <a href="/Slider/Agregar?tipo=bv">Agregar</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <a href="@item.IMAGEN" target="_blank"><img src="@item.IMAGEN" style="width:445px;height:230px;"></a>
                    <span class="card-title"></span>
                </div>
                <div class="card-content">
                    <p>
                        @item.DESCRIPCION - <span class="badge blue" style="color:azure;">@item.ORDEN</span>
                    </p>
                </div>
                <div class="card-action">
                    @Html.ActionLink("Eliminar", "EliminarImagen", new { id = item.ID })
                </div>
            </div>
        </div>
    }
</div>

Admin/Views/Slider/Clasificados.cshtml
@model IEnumerable<Admin.Models.IMAGENES>

@{
    ViewBag.Title = "FonixEresTu";
}

<h2>Clasificados</h2>

<p>
    @*@Html.ActionLink("Agregar", "Agregar")*@
    <a href="/Slider/Agregar?tipo=cl">Agregar</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <a href="@item.IMAGEN" target="_blank"><img src="@item.IMAGEN" style="width:445px;height:230px;"></a>
                    <span class="card-title"></span>
                </div>
                <div class="card-content">
                    <p>
                        @item.DESCRIPCION - <span class="badge blue" style="color:azure;">@item.ORDEN</span>
                    </p>
                </div>
                <div class="card-action">
                    @Html.ActionLink("Eliminar", "EliminarImagen", new { id = item.ID })
                </div>
            </div>
        </div>
    }
</div>

Admin/Views/Slider/ColoresCumple.cshtml
@model IEnumerable<Admin.Models.IMAGENES>
@{
    ViewBag.Title = "ColoresCumple";
}

<h2>ColoresCumple</h2>

<table class="table">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Nombre</th>
            <th>Color</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            @foreach(var i in Model.OrderBy(x=>x.ORDEN))
            {
                <td>@i.DESCRIPCION</td>
            }
        </tr>
    </tbody>
</table>

Admin/Views/Slider/EliminarImagen.cshtml
@model Admin.Models.IMAGENES

@{
    ViewBag.Title = "EliminarImagen";
}

<h2>EliminarImagen</h2>

<h3>Estas seguro de eliminar esta imagen?</h3>
<div>
    <h4>IMAGENES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.APARTADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APARTADO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGEN)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.IMAGEN)*@
            <img src="@Model.IMAGEN" style="width:445px;height:230px;"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Admin/Views/Slider/Eventos.cshtml
@model IEnumerable<Admin.Models.IMAGENES>

@{
    ViewBag.Title = "FonixEresTu";
}

<h2>Clasificados</h2>

<p>
    @*@Html.ActionLink("Agregar", "Agregar")*@
    <a href="/Slider/Agregar?tipo=ev">Agregar</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <a href="@item.IMAGEN" target="_blank"><img src="@item.IMAGEN" style="width:445px;height:230px;"></a>
                    <span class="card-title"></span>
                </div>
                <div class="card-content">
                    <p>
                        @item.DESCRIPCION - <span class="badge blue" style="color:azure;">@item.ORDEN</span>
                    </p>
                </div>
                <div class="card-action">
                    @Html.ActionLink("Eliminar", "EliminarImagen", new { id = item.ID })
                </div>
            </div>
        </div>
    }
</div>

Admin/Views/Slider/FonixEresTu.cshtml
@model IEnumerable<Admin.Models.IMAGENES>

@{
    ViewBag.Title = "FonixEresTu";
}

<h2>FonixEresTu</h2>

<p>
    @*@Html.ActionLink("Agregar", "Agregar")*@
    <a href="/Slider/Agregar?tipo=fet">Agregar</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <a href="@item.IMAGEN" target="_blank"><img src="@item.IMAGEN" style="width:445px;height:230px;" /></a>
                    <span class="card-title"></span>
                </div>
                <div class="card-content">
                    <p>
                        @item.DESCRIPCION - <span class="badge blue" style="color:azure;">@item.ORDEN</span>
                    </p>
                </div>
                <div class="card-action">
                    @Html.ActionLink("Eliminar", "EliminarImagen", new { id = item.ID })
                </div>
            </div>
        </div>
    }
</div>