Admin/Controllers/CodigoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Admin.Models;
using System.Data.Entity;

namespace Admin.Controllers
{
    public class CodigoController : Controller
    {
        private Modelo db = new Modelo();
        // GET: Codigo
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Actualizar()
        {
            var imagen = Request.QueryString["tipo"];
            var query = db.IMAGENES.Where(x => x.DESCRIPCION == imagen);
            return View(query.ToList());
        }


        public ActionResult Editar(int id)
        {
            var query = db.IMAGENES.Find(id);
            ImagenesView imagen = new ImagenesView();
            imagen.ID = query.ID;
            imagen.APARTADO = query.APARTADO;
            imagen.DESCRIPCION = query.DESCRIPCION;
            imagen.IMAGEN = query.IMAGEN;
            return View(imagen);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ImagenesView ImagenesView)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "/imagenes/codigo_etica";

                if (ImagenesView.ImagenFile != null)
                {
                    pic = FilesHelper.UploadPhoto(ImagenesView.ImagenFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var imagen = ToImagenes(ImagenesView);
                imagen.IMAGEN = pic;
                db.Entry(imagen).State = EntityState.Modified;
                db.SaveChanges();

                return Redirect("/Admin/Codigo/Actualizar?tipo=" + ImagenesView.DESCRIPCION);

            }
            return View();
        }


        private IMAGENES ToImagenes(ImagenesView view)
        {
            return new IMAGENES
            {
                ID = view.ID,
                APARTADO = view.APARTADO,
                IMAGEN = view.IMAGEN,
                ORDEN = view.ORDEN,
                DESCRIPCION = view.DESCRIPCION
            };
        }
    }
}

Admin/Views/Codigo/Actualizar.cshtml
@model Admin.Models.IMAGENES

@{
    ViewBag.Title = "ActualizarImagen";
}

<h2>ActualizarImagen</h2>

<div>
    <h4>IMAGENES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.APARTADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APARTADO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGEN)
        </dt>

        <dd>
            @if (Request.QueryString["tipo"] == "Imagen")
            {
                <img src="@Model.IMAGEN" />
            }
            
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.ID }) |
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

Admin/Views/Codigo/Editar.cshtml
@model Admin.Models.ImagenesView

@{
    ViewBag.Title = "Agregar";
}


@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <h3>@ViewBag.Error</h3>
}
<h2>Agregar</h2>


@using (Html.BeginForm("Editar", "Codigo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>IMAGENES</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.APARTADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="APARTADO" id="APARTADO" value="CODIGO_ETICA">
                @Html.ValidationMessageFor(model => model.APARTADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(modelo => modelo.ImagenFile, new { type = "file" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}